name: Build

# Triggers the workflow on push or pull request events (for any branch in a repository)
on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.61.0 # MSRV
    steps:
      - uses: actions/checkout@v2
      # Important preparation step: override the latest default Rust version in GitHub CI
      # with the current value of the iteration in the "strategy.matrix.rust"-array.
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install required Linux packages for "audio-visualizer"/cpal/minifb
        run: sudo apt update && sudo apt -y install libasound2-dev libxkbcommon-dev

      # build with all features/fft implementations
      - run: cargo build --all-targets
      - run: cargo build --all-targets --no-default-features --features "rustfft-complex"
      - run: cargo build --all-targets --no-default-features --features "microfft-real"

      # run tests with all features/fft implementations
      - run: cargo test --all-targets
      - run: cargo test --all-targets --no-default-features --features "rustfft-complex"
      - run: cargo test --all-targets --no-default-features --features "microfft-real"

      # run benchmark: right now, there is no reporting or so from the results
      - run: cargo bench

      # test `no_std`-build with all features/fft implementations
      - run: rustup target add thumbv7em-none-eabihf
      - run: cargo check --target thumbv7em-none-eabihf --no-default-features --features "microfft-real"

      # run examples with all features/fft implementations
      - run: cargo run --release --example mp3-samples
      - run: cargo run --release --example mp3-samples --no-default-features --features "rustfft-complex"
      - run: cargo run --release --example mp3-samples --no-default-features --features "microfft-real"

  style_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.61.0 # MSRV
    steps:
      - uses: actions/checkout@v2
      # Important preparation step: override the latest default Rust version in GitHub CI
      # with the current value of the iteration in the "strategy.matrix.rust"-array.
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rustfmt (checks all source code/all features)
        run: cargo fmt -- --check
      - name: Clippy (default feature)
        run: cargo clippy
      - name: Clippy (rustfft-complex)
        run: cargo clippy --no-default-features --features "rustfft-complex"
      - name: Clippy (microfft-real)
        run: cargo clippy --no-default-features --features "microfft-real"
      - name: Rustdoc (default feature)
        run: cargo doc
      - name: Rustdoc (rustfft-complex)
        run: cargo doc --no-default-features --features "rustfft-complex"
      - name: Rustdoc (microfft-real)
        run: cargo doc --no-default-features --features "microfft-real"
